/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as LandingBlogRouteImport } from './routes/_landing/blog'
import { Route as LandingCompanyRouteImport } from './routes/_landing/company'
import { Route as LandingDownloadsRouteImport } from './routes/_landing/downloads'
import { Route as LandingLegalRouteImport } from './routes/_landing/legal'
import { Route as LandingStartupProgramRouteImport } from './routes/_landing/startup-program'
import { Route as ApiStartupProgramRouteImport } from './routes/api/startup-program'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthBackupCodesRouteImport } from './routes/auth/backup-codes'
import { Route as AuthEmailOtpRouteImport } from './routes/auth/email-otp'
import { Route as AuthTotpRouteImport } from './routes/auth/totp'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardOrganizationRouteImport } from './routes/_authenticated/dashboard/$organization'
import { Route as AuthenticatedOnboardingProductRouteImport } from './routes/_authenticated/onboarding/product'
import { Route as AuthenticatedOnboardingValidateDescriptionRouteImport } from './routes/_authenticated/onboarding/validate-description'
import { Route as LandingBlogIndexRouteImport } from './routes/_landing/blog/index'
import { Route as LandingBlogIntroducingPolarPlansRouteImport } from './routes/_landing/blog/introducing-polar-plans'
import { Route as LandingBlogMitchellHashimotoJoinsPolarAsAnAdvisorRouteImport } from './routes/_landing/blog/mitchell-hashimoto-joins-polar-as-an-advisor'
import { Route as LandingBlogOrbitLlmSafeDesignSystemRouteImport } from './routes/_landing/blog/orbit-llm-safe-design-system'
import { Route as LandingBlogPolarSeedAnnouncementRouteImport } from './routes/_landing/blog/polar-seed-announcement'
import { Route as LandingBlogPromptAStartup2026RouteImport } from './routes/_landing/blog/prompt-a-startup-2026'
import { Route as LandingCustomersStillaAiRouteImport } from './routes/_landing/customers/stilla-ai'
import { Route as LandingFeaturesCostInsightsRouteImport } from './routes/_landing/features/cost-insights'
import { Route as LandingFeaturesCreditsRouteImport } from './routes/_landing/features/credits'
import { Route as LandingFeaturesDiscountsRouteImport } from './routes/_landing/features/discounts'
import { Route as LandingFeaturesFinanceRouteImport } from './routes/_landing/features/finance'
import { Route as LandingFeaturesMerchantOfRecordRouteImport } from './routes/_landing/features/merchant-of-record'
import { Route as LandingFeaturesSeatsRouteImport } from './routes/_landing/features/seats'
import { Route as LandingFeaturesSubscriptionsRouteImport } from './routes/_landing/features/subscriptions'
import { Route as LandingFeaturesTrialsRouteImport } from './routes/_landing/features/trials'
import { Route as LandingFeaturesUsageBillingRouteImport } from './routes/_landing/features/usage-billing'
import { Route as LandingLegalIndexRouteImport } from './routes/_landing/legal/index'
import { Route as LandingLegalAcceptableUsePolicyRouteImport } from './routes/_landing/legal/acceptable-use-policy'
import { Route as LandingLegalCheckoutBuyerTermsRouteImport } from './routes/_landing/legal/checkout-buyer-terms'
import { Route as LandingLegalDataProcessingAddendumRouteImport } from './routes/_landing/legal/data-processing-addendum'
import { Route as LandingLegalMasterServicesTermsRouteImport } from './routes/_landing/legal/master-services-terms'
import { Route as LandingLegalPaymentProcessorPartnersRouteImport } from './routes/_landing/legal/payment-processor-partners'
import { Route as LandingLegalPrivacyPolicyRouteImport } from './routes/_landing/legal/privacy-policy'
import { Route as LandingLegalSubProcessorsRouteImport } from './routes/_landing/legal/sub-processors'
import { Route as LandingResourcesIndexRouteImport } from './routes/_landing/resources/index'
import { Route as LandingResourcesMerchantOfRecordRouteImport } from './routes/_landing/resources/merchant-of-record'
import { Route as LandingResourcesPricingRouteImport } from './routes/_landing/resources/pricing'
import { Route as LandingResourcesWhyRouteImport } from './routes/_landing/resources/why'
import { Route as AuthSsoSlugRouteImport } from './routes/auth/sso/$slug'
import { Route as AuthenticatedDashboardOrganizationIndexRouteImport } from './routes/_authenticated/dashboard/$organization/index'
import { Route as LandingResourcesComparisonLemonSqueezyRouteImport } from './routes/_landing/resources/comparison/lemon-squeezy'
import { Route as LandingResourcesComparisonPaddleRouteImport } from './routes/_landing/resources/comparison/paddle'
import { Route as LandingResourcesComparisonStripeRouteImport } from './routes/_landing/resources/comparison/stripe'
import { Route as AuthenticatedDashboardOrganizationProductsIndexRouteImport } from './routes/_authenticated/dashboard/$organization/products/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingBlogRoute = LandingBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LandingRoute,
} as any)
const LandingCompanyRoute = LandingCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => LandingRoute,
} as any)
const LandingDownloadsRoute = LandingDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => LandingRoute,
} as any)
const LandingLegalRoute = LandingLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => LandingRoute,
} as any)
const LandingStartupProgramRoute = LandingStartupProgramRouteImport.update({
  id: '/startup-program',
  path: '/startup-program',
  getParentRoute: () => LandingRoute,
} as any)
const ApiStartupProgramRoute = ApiStartupProgramRouteImport.update({
  id: '/api/startup-program',
  path: '/api/startup-program',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBackupCodesRoute = AuthBackupCodesRouteImport.update({
  id: '/backup-codes',
  path: '/backup-codes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailOtpRoute = AuthEmailOtpRouteImport.update({
  id: '/email-otp',
  path: '/email-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTotpRoute = AuthTotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardOrganizationRoute =
  AuthenticatedDashboardOrganizationRouteImport.update({
    id: '/dashboard/$organization',
    path: '/dashboard/$organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingProductRoute =
  AuthenticatedOnboardingProductRouteImport.update({
    id: '/product',
    path: '/product',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingValidateDescriptionRoute =
  AuthenticatedOnboardingValidateDescriptionRouteImport.update({
    id: '/validate-description',
    path: '/validate-description',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const LandingBlogIndexRoute = LandingBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingBlogRoute,
} as any)
const LandingBlogIntroducingPolarPlansRoute =
  LandingBlogIntroducingPolarPlansRouteImport.update({
    id: '/introducing-polar-plans',
    path: '/introducing-polar-plans',
    getParentRoute: () => LandingBlogRoute,
  } as any)
const LandingBlogMitchellHashimotoJoinsPolarAsAnAdvisorRoute =
  LandingBlogMitchellHashimotoJoinsPolarAsAnAdvisorRouteImport.update({
    id: '/mitchell-hashimoto-joins-polar-as-an-advisor',
    path: '/mitchell-hashimoto-joins-polar-as-an-advisor',
    getParentRoute: () => LandingBlogRoute,
  } as any)
const LandingBlogOrbitLlmSafeDesignSystemRoute =
  LandingBlogOrbitLlmSafeDesignSystemRouteImport.update({
    id: '/orbit-llm-safe-design-system',
    path: '/orbit-llm-safe-design-system',
    getParentRoute: () => LandingBlogRoute,
  } as any)
const LandingBlogPolarSeedAnnouncementRoute =
  LandingBlogPolarSeedAnnouncementRouteImport.update({
    id: '/polar-seed-announcement',
    path: '/polar-seed-announcement',
    getParentRoute: () => LandingBlogRoute,
  } as any)
const LandingBlogPromptAStartup2026Route =
  LandingBlogPromptAStartup2026RouteImport.update({
    id: '/prompt-a-startup-2026',
    path: '/prompt-a-startup-2026',
    getParentRoute: () => LandingBlogRoute,
  } as any)
const LandingCustomersStillaAiRoute =
  LandingCustomersStillaAiRouteImport.update({
    id: '/customers/stilla-ai',
    path: '/customers/stilla-ai',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingFeaturesCostInsightsRoute =
  LandingFeaturesCostInsightsRouteImport.update({
    id: '/features/cost-insights',
    path: '/features/cost-insights',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingFeaturesCreditsRoute = LandingFeaturesCreditsRouteImport.update({
  id: '/features/credits',
  path: '/features/credits',
  getParentRoute: () => LandingRoute,
} as any)
const LandingFeaturesDiscountsRoute =
  LandingFeaturesDiscountsRouteImport.update({
    id: '/features/discounts',
    path: '/features/discounts',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingFeaturesFinanceRoute = LandingFeaturesFinanceRouteImport.update({
  id: '/features/finance',
  path: '/features/finance',
  getParentRoute: () => LandingRoute,
} as any)
const LandingFeaturesMerchantOfRecordRoute =
  LandingFeaturesMerchantOfRecordRouteImport.update({
    id: '/features/merchant-of-record',
    path: '/features/merchant-of-record',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingFeaturesSeatsRoute = LandingFeaturesSeatsRouteImport.update({
  id: '/features/seats',
  path: '/features/seats',
  getParentRoute: () => LandingRoute,
} as any)
const LandingFeaturesSubscriptionsRoute =
  LandingFeaturesSubscriptionsRouteImport.update({
    id: '/features/subscriptions',
    path: '/features/subscriptions',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingFeaturesTrialsRoute = LandingFeaturesTrialsRouteImport.update({
  id: '/features/trials',
  path: '/features/trials',
  getParentRoute: () => LandingRoute,
} as any)
const LandingFeaturesUsageBillingRoute =
  LandingFeaturesUsageBillingRouteImport.update({
    id: '/features/usage-billing',
    path: '/features/usage-billing',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingLegalIndexRoute = LandingLegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingLegalRoute,
} as any)
const LandingLegalAcceptableUsePolicyRoute =
  LandingLegalAcceptableUsePolicyRouteImport.update({
    id: '/acceptable-use-policy',
    path: '/acceptable-use-policy',
    getParentRoute: () => LandingLegalRoute,
  } as any)
const LandingLegalCheckoutBuyerTermsRoute =
  LandingLegalCheckoutBuyerTermsRouteImport.update({
    id: '/checkout-buyer-terms',
    path: '/checkout-buyer-terms',
    getParentRoute: () => LandingLegalRoute,
  } as any)
const LandingLegalDataProcessingAddendumRoute =
  LandingLegalDataProcessingAddendumRouteImport.update({
    id: '/data-processing-addendum',
    path: '/data-processing-addendum',
    getParentRoute: () => LandingLegalRoute,
  } as any)
const LandingLegalMasterServicesTermsRoute =
  LandingLegalMasterServicesTermsRouteImport.update({
    id: '/master-services-terms',
    path: '/master-services-terms',
    getParentRoute: () => LandingLegalRoute,
  } as any)
const LandingLegalPaymentProcessorPartnersRoute =
  LandingLegalPaymentProcessorPartnersRouteImport.update({
    id: '/payment-processor-partners',
    path: '/payment-processor-partners',
    getParentRoute: () => LandingLegalRoute,
  } as any)
const LandingLegalPrivacyPolicyRoute =
  LandingLegalPrivacyPolicyRouteImport.update({
    id: '/privacy-policy',
    path: '/privacy-policy',
    getParentRoute: () => LandingLegalRoute,
  } as any)
const LandingLegalSubProcessorsRoute =
  LandingLegalSubProcessorsRouteImport.update({
    id: '/sub-processors',
    path: '/sub-processors',
    getParentRoute: () => LandingLegalRoute,
  } as any)
const LandingResourcesIndexRoute = LandingResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingResourcesMerchantOfRecordRoute =
  LandingResourcesMerchantOfRecordRouteImport.update({
    id: '/resources/merchant-of-record',
    path: '/resources/merchant-of-record',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingResourcesPricingRoute = LandingResourcesPricingRouteImport.update({
  id: '/resources/pricing',
  path: '/resources/pricing',
  getParentRoute: () => LandingRoute,
} as any)
const LandingResourcesWhyRoute = LandingResourcesWhyRouteImport.update({
  id: '/resources/why',
  path: '/resources/why',
  getParentRoute: () => LandingRoute,
} as any)
const AuthSsoSlugRoute = AuthSsoSlugRouteImport.update({
  id: '/sso/$slug',
  path: '/sso/$slug',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardOrganizationIndexRoute =
  AuthenticatedDashboardOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardOrganizationRoute,
  } as any)
const LandingResourcesComparisonLemonSqueezyRoute =
  LandingResourcesComparisonLemonSqueezyRouteImport.update({
    id: '/resources/comparison/lemon-squeezy',
    path: '/resources/comparison/lemon-squeezy',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingResourcesComparisonPaddleRoute =
  LandingResourcesComparisonPaddleRouteImport.update({
    id: '/resources/comparison/paddle',
    path: '/resources/comparison/paddle',
    getParentRoute: () => LandingRoute,
  } as any)
const LandingResourcesComparisonStripeRoute =
  LandingResourcesComparisonStripeRouteImport.update({
    id: '/resources/comparison/stripe',
    path: '/resources/comparison/stripe',
    getParentRoute: () => LandingRoute,
  } as any)
const AuthenticatedDashboardOrganizationProductsIndexRoute =
  AuthenticatedDashboardOrganizationProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedDashboardOrganizationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/blog': typeof LandingBlogRouteWithChildren
  '/company': typeof LandingCompanyRoute
  '/downloads': typeof LandingDownloadsRoute
  '/legal': typeof LandingLegalRouteWithChildren
  '/startup-program': typeof LandingStartupProgramRoute
  '/api/startup-program': typeof ApiStartupProgramRoute
  '/auth/backup-codes': typeof AuthBackupCodesRoute
  '/auth/email-otp': typeof AuthEmailOtpRoute
  '/auth/totp': typeof AuthTotpRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/$organization': typeof AuthenticatedDashboardOrganizationRouteWithChildren
  '/onboarding/product': typeof AuthenticatedOnboardingProductRoute
  '/onboarding/validate-description': typeof AuthenticatedOnboardingValidateDescriptionRoute
  '/blog/introducing-polar-plans': typeof LandingBlogIntroducingPolarPlansRoute
  '/blog/mitchell-hashimoto-joins-polar-as-an-advisor': typeof LandingBlogMitchellHashimotoJoinsPolarAsAnAdvisorRoute
  '/blog/orbit-llm-safe-design-system': typeof LandingBlogOrbitLlmSafeDesignSystemRoute
  '/blog/polar-seed-announcement': typeof LandingBlogPolarSeedAnnouncementRoute
  '/blog/prompt-a-startup-2026': typeof LandingBlogPromptAStartup2026Route
  '/customers/stilla-ai': typeof LandingCustomersStillaAiRoute
  '/features/cost-insights': typeof LandingFeaturesCostInsightsRoute
  '/features/credits': typeof LandingFeaturesCreditsRoute
  '/features/discounts': typeof LandingFeaturesDiscountsRoute
  '/features/finance': typeof LandingFeaturesFinanceRoute
  '/features/merchant-of-record': typeof LandingFeaturesMerchantOfRecordRoute
  '/features/seats': typeof LandingFeaturesSeatsRoute
  '/features/subscriptions': typeof LandingFeaturesSubscriptionsRoute
  '/features/trials': typeof LandingFeaturesTrialsRoute
  '/features/usage-billing': typeof LandingFeaturesUsageBillingRoute
  '/legal/acceptable-use-policy': typeof LandingLegalAcceptableUsePolicyRoute
  '/legal/checkout-buyer-terms': typeof LandingLegalCheckoutBuyerTermsRoute
  '/legal/data-processing-addendum': typeof LandingLegalDataProcessingAddendumRoute
  '/legal/master-services-terms': typeof LandingLegalMasterServicesTermsRoute
  '/legal/payment-processor-partners': typeof LandingLegalPaymentProcessorPartnersRoute
  '/legal/privacy-policy': typeof LandingLegalPrivacyPolicyRoute
  '/legal/sub-processors': typeof LandingLegalSubProcessorsRoute
  '/resources/merchant-of-record': typeof LandingResourcesMerchantOfRecordRoute
  '/resources/pricing': typeof LandingResourcesPricingRoute
  '/resources/why': typeof LandingResourcesWhyRoute
  '/auth/sso/$slug': typeof AuthSsoSlugRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/blog/': typeof LandingBlogIndexRoute
  '/legal/': typeof LandingLegalIndexRoute
  '/resources/': typeof LandingResourcesIndexRoute
  '/resources/comparison/lemon-squeezy': typeof LandingResourcesComparisonLemonSqueezyRoute
  '/resources/comparison/paddle': typeof LandingResourcesComparisonPaddleRoute
  '/resources/comparison/stripe': typeof LandingResourcesComparisonStripeRoute
  '/dashboard/$organization/': typeof AuthenticatedDashboardOrganizationIndexRoute
  '/dashboard/$organization/products/': typeof AuthenticatedDashboardOrganizationProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/company': typeof LandingCompanyRoute
  '/downloads': typeof LandingDownloadsRoute
  '/startup-program': typeof LandingStartupProgramRoute
  '/api/startup-program': typeof ApiStartupProgramRoute
  '/auth/backup-codes': typeof AuthBackupCodesRoute
  '/auth/email-otp': typeof AuthEmailOtpRoute
  '/auth/totp': typeof AuthTotpRoute
  '/auth': typeof AuthIndexRoute
  '/onboarding/product': typeof AuthenticatedOnboardingProductRoute
  '/onboarding/validate-description': typeof AuthenticatedOnboardingValidateDescriptionRoute
  '/blog/introducing-polar-plans': typeof LandingBlogIntroducingPolarPlansRoute
  '/blog/mitchell-hashimoto-joins-polar-as-an-advisor': typeof LandingBlogMitchellHashimotoJoinsPolarAsAnAdvisorRoute
  '/blog/orbit-llm-safe-design-system': typeof LandingBlogOrbitLlmSafeDesignSystemRoute
  '/blog/polar-seed-announcement': typeof LandingBlogPolarSeedAnnouncementRoute
  '/blog/prompt-a-startup-2026': typeof LandingBlogPromptAStartup2026Route
  '/customers/stilla-ai': typeof LandingCustomersStillaAiRoute
  '/features/cost-insights': typeof LandingFeaturesCostInsightsRoute
  '/features/credits': typeof LandingFeaturesCreditsRoute
  '/features/discounts': typeof LandingFeaturesDiscountsRoute
  '/features/finance': typeof LandingFeaturesFinanceRoute
  '/features/merchant-of-record': typeof LandingFeaturesMerchantOfRecordRoute
  '/features/seats': typeof LandingFeaturesSeatsRoute
  '/features/subscriptions': typeof LandingFeaturesSubscriptionsRoute
  '/features/trials': typeof LandingFeaturesTrialsRoute
  '/features/usage-billing': typeof LandingFeaturesUsageBillingRoute
  '/legal/acceptable-use-policy': typeof LandingLegalAcceptableUsePolicyRoute
  '/legal/checkout-buyer-terms': typeof LandingLegalCheckoutBuyerTermsRoute
  '/legal/data-processing-addendum': typeof LandingLegalDataProcessingAddendumRoute
  '/legal/master-services-terms': typeof LandingLegalMasterServicesTermsRoute
  '/legal/payment-processor-partners': typeof LandingLegalPaymentProcessorPartnersRoute
  '/legal/privacy-policy': typeof LandingLegalPrivacyPolicyRoute
  '/legal/sub-processors': typeof LandingLegalSubProcessorsRoute
  '/resources/merchant-of-record': typeof LandingResourcesMerchantOfRecordRoute
  '/resources/pricing': typeof LandingResourcesPricingRoute
  '/resources/why': typeof LandingResourcesWhyRoute
  '/auth/sso/$slug': typeof AuthSsoSlugRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/blog': typeof LandingBlogIndexRoute
  '/legal': typeof LandingLegalIndexRoute
  '/resources': typeof LandingResourcesIndexRoute
  '/resources/comparison/lemon-squeezy': typeof LandingResourcesComparisonLemonSqueezyRoute
  '/resources/comparison/paddle': typeof LandingResourcesComparisonPaddleRoute
  '/resources/comparison/stripe': typeof LandingResourcesComparisonStripeRoute
  '/dashboard/$organization': typeof AuthenticatedDashboardOrganizationIndexRoute
  '/dashboard/$organization/products': typeof AuthenticatedDashboardOrganizationProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_landing': typeof LandingRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/_landing/blog': typeof LandingBlogRouteWithChildren
  '/_landing/company': typeof LandingCompanyRoute
  '/_landing/downloads': typeof LandingDownloadsRoute
  '/_landing/legal': typeof LandingLegalRouteWithChildren
  '/_landing/startup-program': typeof LandingStartupProgramRoute
  '/api/startup-program': typeof ApiStartupProgramRoute
  '/auth/backup-codes': typeof AuthBackupCodesRoute
  '/auth/email-otp': typeof AuthEmailOtpRoute
  '/auth/totp': typeof AuthTotpRoute
  '/_landing/': typeof LandingIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/dashboard/$organization': typeof AuthenticatedDashboardOrganizationRouteWithChildren
  '/_authenticated/onboarding/product': typeof AuthenticatedOnboardingProductRoute
  '/_authenticated/onboarding/validate-description': typeof AuthenticatedOnboardingValidateDescriptionRoute
  '/_landing/blog/introducing-polar-plans': typeof LandingBlogIntroducingPolarPlansRoute
  '/_landing/blog/mitchell-hashimoto-joins-polar-as-an-advisor': typeof LandingBlogMitchellHashimotoJoinsPolarAsAnAdvisorRoute
  '/_landing/blog/orbit-llm-safe-design-system': typeof LandingBlogOrbitLlmSafeDesignSystemRoute
  '/_landing/blog/polar-seed-announcement': typeof LandingBlogPolarSeedAnnouncementRoute
  '/_landing/blog/prompt-a-startup-2026': typeof LandingBlogPromptAStartup2026Route
  '/_landing/customers/stilla-ai': typeof LandingCustomersStillaAiRoute
  '/_landing/features/cost-insights': typeof LandingFeaturesCostInsightsRoute
  '/_landing/features/credits': typeof LandingFeaturesCreditsRoute
  '/_landing/features/discounts': typeof LandingFeaturesDiscountsRoute
  '/_landing/features/finance': typeof LandingFeaturesFinanceRoute
  '/_landing/features/merchant-of-record': typeof LandingFeaturesMerchantOfRecordRoute
  '/_landing/features/seats': typeof LandingFeaturesSeatsRoute
  '/_landing/features/subscriptions': typeof LandingFeaturesSubscriptionsRoute
  '/_landing/features/trials': typeof LandingFeaturesTrialsRoute
  '/_landing/features/usage-billing': typeof LandingFeaturesUsageBillingRoute
  '/_landing/legal/acceptable-use-policy': typeof LandingLegalAcceptableUsePolicyRoute
  '/_landing/legal/checkout-buyer-terms': typeof LandingLegalCheckoutBuyerTermsRoute
  '/_landing/legal/data-processing-addendum': typeof LandingLegalDataProcessingAddendumRoute
  '/_landing/legal/master-services-terms': typeof LandingLegalMasterServicesTermsRoute
  '/_landing/legal/payment-processor-partners': typeof LandingLegalPaymentProcessorPartnersRoute
  '/_landing/legal/privacy-policy': typeof LandingLegalPrivacyPolicyRoute
  '/_landing/legal/sub-processors': typeof LandingLegalSubProcessorsRoute
  '/_landing/resources/merchant-of-record': typeof LandingResourcesMerchantOfRecordRoute
  '/_landing/resources/pricing': typeof LandingResourcesPricingRoute
  '/_landing/resources/why': typeof LandingResourcesWhyRoute
  '/auth/sso/$slug': typeof AuthSsoSlugRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_landing/blog/': typeof LandingBlogIndexRoute
  '/_landing/legal/': typeof LandingLegalIndexRoute
  '/_landing/resources/': typeof LandingResourcesIndexRoute
  '/_landing/resources/comparison/lemon-squeezy': typeof LandingResourcesComparisonLemonSqueezyRoute
  '/_landing/resources/comparison/paddle': typeof LandingResourcesComparisonPaddleRoute
  '/_landing/resources/comparison/stripe': typeof LandingResourcesComparisonStripeRoute
  '/_authenticated/dashboard/$organization/': typeof AuthenticatedDashboardOrganizationIndexRoute
  '/_authenticated/dashboard/$organization/products/': typeof AuthenticatedDashboardOrganizationProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/blog'
    | '/company'
    | '/downloads'
    | '/legal'
    | '/startup-program'
    | '/api/startup-program'
    | '/auth/backup-codes'
    | '/auth/email-otp'
    | '/auth/totp'
    | '/auth/'
    | '/dashboard/$organization'
    | '/onboarding/product'
    | '/onboarding/validate-description'
    | '/blog/introducing-polar-plans'
    | '/blog/mitchell-hashimoto-joins-polar-as-an-advisor'
    | '/blog/orbit-llm-safe-design-system'
    | '/blog/polar-seed-announcement'
    | '/blog/prompt-a-startup-2026'
    | '/customers/stilla-ai'
    | '/features/cost-insights'
    | '/features/credits'
    | '/features/discounts'
    | '/features/finance'
    | '/features/merchant-of-record'
    | '/features/seats'
    | '/features/subscriptions'
    | '/features/trials'
    | '/features/usage-billing'
    | '/legal/acceptable-use-policy'
    | '/legal/checkout-buyer-terms'
    | '/legal/data-processing-addendum'
    | '/legal/master-services-terms'
    | '/legal/payment-processor-partners'
    | '/legal/privacy-policy'
    | '/legal/sub-processors'
    | '/resources/merchant-of-record'
    | '/resources/pricing'
    | '/resources/why'
    | '/auth/sso/$slug'
    | '/dashboard/'
    | '/blog/'
    | '/legal/'
    | '/resources/'
    | '/resources/comparison/lemon-squeezy'
    | '/resources/comparison/paddle'
    | '/resources/comparison/stripe'
    | '/dashboard/$organization/'
    | '/dashboard/$organization/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/company'
    | '/downloads'
    | '/startup-program'
    | '/api/startup-program'
    | '/auth/backup-codes'
    | '/auth/email-otp'
    | '/auth/totp'
    | '/auth'
    | '/onboarding/product'
    | '/onboarding/validate-description'
    | '/blog/introducing-polar-plans'
    | '/blog/mitchell-hashimoto-joins-polar-as-an-advisor'
    | '/blog/orbit-llm-safe-design-system'
    | '/blog/polar-seed-announcement'
    | '/blog/prompt-a-startup-2026'
    | '/customers/stilla-ai'
    | '/features/cost-insights'
    | '/features/credits'
    | '/features/discounts'
    | '/features/finance'
    | '/features/merchant-of-record'
    | '/features/seats'
    | '/features/subscriptions'
    | '/features/trials'
    | '/features/usage-billing'
    | '/legal/acceptable-use-policy'
    | '/legal/checkout-buyer-terms'
    | '/legal/data-processing-addendum'
    | '/legal/master-services-terms'
    | '/legal/payment-processor-partners'
    | '/legal/privacy-policy'
    | '/legal/sub-processors'
    | '/resources/merchant-of-record'
    | '/resources/pricing'
    | '/resources/why'
    | '/auth/sso/$slug'
    | '/dashboard'
    | '/blog'
    | '/legal'
    | '/resources'
    | '/resources/comparison/lemon-squeezy'
    | '/resources/comparison/paddle'
    | '/resources/comparison/stripe'
    | '/dashboard/$organization'
    | '/dashboard/$organization/products'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_landing'
    | '/auth'
    | '/_authenticated/onboarding'
    | '/_landing/blog'
    | '/_landing/company'
    | '/_landing/downloads'
    | '/_landing/legal'
    | '/_landing/startup-program'
    | '/api/startup-program'
    | '/auth/backup-codes'
    | '/auth/email-otp'
    | '/auth/totp'
    | '/_landing/'
    | '/auth/'
    | '/_authenticated/dashboard/$organization'
    | '/_authenticated/onboarding/product'
    | '/_authenticated/onboarding/validate-description'
    | '/_landing/blog/introducing-polar-plans'
    | '/_landing/blog/mitchell-hashimoto-joins-polar-as-an-advisor'
    | '/_landing/blog/orbit-llm-safe-design-system'
    | '/_landing/blog/polar-seed-announcement'
    | '/_landing/blog/prompt-a-startup-2026'
    | '/_landing/customers/stilla-ai'
    | '/_landing/features/cost-insights'
    | '/_landing/features/credits'
    | '/_landing/features/discounts'
    | '/_landing/features/finance'
    | '/_landing/features/merchant-of-record'
    | '/_landing/features/seats'
    | '/_landing/features/subscriptions'
    | '/_landing/features/trials'
    | '/_landing/features/usage-billing'
    | '/_landing/legal/acceptable-use-policy'
    | '/_landing/legal/checkout-buyer-terms'
    | '/_landing/legal/data-processing-addendum'
    | '/_landing/legal/master-services-terms'
    | '/_landing/legal/payment-processor-partners'
    | '/_landing/legal/privacy-policy'
    | '/_landing/legal/sub-processors'
    | '/_landing/resources/merchant-of-record'
    | '/_landing/resources/pricing'
    | '/_landing/resources/why'
    | '/auth/sso/$slug'
    | '/_authenticated/dashboard/'
    | '/_landing/blog/'
    | '/_landing/legal/'
    | '/_landing/resources/'
    | '/_landing/resources/comparison/lemon-squeezy'
    | '/_landing/resources/comparison/paddle'
    | '/_landing/resources/comparison/stripe'
    | '/_authenticated/dashboard/$organization/'
    | '/_authenticated/dashboard/$organization/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LandingRoute: typeof LandingRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiStartupProgramRoute: typeof ApiStartupProgramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/blog': {
      id: '/_landing/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof LandingBlogRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/company': {
      id: '/_landing/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof LandingCompanyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/downloads': {
      id: '/_landing/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof LandingDownloadsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/legal': {
      id: '/_landing/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LandingLegalRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/startup-program': {
      id: '/_landing/startup-program'
      path: '/startup-program'
      fullPath: '/startup-program'
      preLoaderRoute: typeof LandingStartupProgramRouteImport
      parentRoute: typeof LandingRoute
    }
    '/api/startup-program': {
      id: '/api/startup-program'
      path: '/api/startup-program'
      fullPath: '/api/startup-program'
      preLoaderRoute: typeof ApiStartupProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/backup-codes': {
      id: '/auth/backup-codes'
      path: '/backup-codes'
      fullPath: '/auth/backup-codes'
      preLoaderRoute: typeof AuthBackupCodesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/email-otp': {
      id: '/auth/email-otp'
      path: '/email-otp'
      fullPath: '/auth/email-otp'
      preLoaderRoute: typeof AuthEmailOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/totp': {
      id: '/auth/totp'
      path: '/totp'
      fullPath: '/auth/totp'
      preLoaderRoute: typeof AuthTotpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/$organization': {
      id: '/_authenticated/dashboard/$organization'
      path: '/dashboard/$organization'
      fullPath: '/dashboard/$organization'
      preLoaderRoute: typeof AuthenticatedDashboardOrganizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/product': {
      id: '/_authenticated/onboarding/product'
      path: '/product'
      fullPath: '/onboarding/product'
      preLoaderRoute: typeof AuthenticatedOnboardingProductRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/validate-description': {
      id: '/_authenticated/onboarding/validate-description'
      path: '/validate-description'
      fullPath: '/onboarding/validate-description'
      preLoaderRoute: typeof AuthenticatedOnboardingValidateDescriptionRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_landing/blog/': {
      id: '/_landing/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof LandingBlogIndexRouteImport
      parentRoute: typeof LandingBlogRoute
    }
    '/_landing/blog/introducing-polar-plans': {
      id: '/_landing/blog/introducing-polar-plans'
      path: '/introducing-polar-plans'
      fullPath: '/blog/introducing-polar-plans'
      preLoaderRoute: typeof LandingBlogIntroducingPolarPlansRouteImport
      parentRoute: typeof LandingBlogRoute
    }
    '/_landing/blog/mitchell-hashimoto-joins-polar-as-an-advisor': {
      id: '/_landing/blog/mitchell-hashimoto-joins-polar-as-an-advisor'
      path: '/mitchell-hashimoto-joins-polar-as-an-advisor'
      fullPath: '/blog/mitchell-hashimoto-joins-polar-as-an-advisor'
      preLoaderRoute: typeof LandingBlogMitchellHashimotoJoinsPolarAsAnAdvisorRouteImport
      parentRoute: typeof LandingBlogRoute
    }
    '/_landing/blog/orbit-llm-safe-design-system': {
      id: '/_landing/blog/orbit-llm-safe-design-system'
      path: '/orbit-llm-safe-design-system'
      fullPath: '/blog/orbit-llm-safe-design-system'
      preLoaderRoute: typeof LandingBlogOrbitLlmSafeDesignSystemRouteImport
      parentRoute: typeof LandingBlogRoute
    }
    '/_landing/blog/polar-seed-announcement': {
      id: '/_landing/blog/polar-seed-announcement'
      path: '/polar-seed-announcement'
      fullPath: '/blog/polar-seed-announcement'
      preLoaderRoute: typeof LandingBlogPolarSeedAnnouncementRouteImport
      parentRoute: typeof LandingBlogRoute
    }
    '/_landing/blog/prompt-a-startup-2026': {
      id: '/_landing/blog/prompt-a-startup-2026'
      path: '/prompt-a-startup-2026'
      fullPath: '/blog/prompt-a-startup-2026'
      preLoaderRoute: typeof LandingBlogPromptAStartup2026RouteImport
      parentRoute: typeof LandingBlogRoute
    }
    '/_landing/customers/stilla-ai': {
      id: '/_landing/customers/stilla-ai'
      path: '/customers/stilla-ai'
      fullPath: '/customers/stilla-ai'
      preLoaderRoute: typeof LandingCustomersStillaAiRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/features/cost-insights': {
      id: '/_landing/features/cost-insights'
      path: '/features/cost-insights'
      fullPath: '/features/cost-insights'
      preLoaderRoute: typeof LandingFeaturesCostInsightsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/features/credits': {
      id: '/_landing/features/credits'
      path: '/features/credits'
      fullPath: '/features/credits'
      preLoaderRoute: typeof LandingFeaturesCreditsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/features/discounts': {
      id: '/_landing/features/discounts'
      path: '/features/discounts'
      fullPath: '/features/discounts'
      preLoaderRoute: typeof LandingFeaturesDiscountsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/features/finance': {
      id: '/_landing/features/finance'
      path: '/features/finance'
      fullPath: '/features/finance'
      preLoaderRoute: typeof LandingFeaturesFinanceRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/features/merchant-of-record': {
      id: '/_landing/features/merchant-of-record'
      path: '/features/merchant-of-record'
      fullPath: '/features/merchant-of-record'
      preLoaderRoute: typeof LandingFeaturesMerchantOfRecordRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/features/seats': {
      id: '/_landing/features/seats'
      path: '/features/seats'
      fullPath: '/features/seats'
      preLoaderRoute: typeof LandingFeaturesSeatsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/features/subscriptions': {
      id: '/_landing/features/subscriptions'
      path: '/features/subscriptions'
      fullPath: '/features/subscriptions'
      preLoaderRoute: typeof LandingFeaturesSubscriptionsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/features/trials': {
      id: '/_landing/features/trials'
      path: '/features/trials'
      fullPath: '/features/trials'
      preLoaderRoute: typeof LandingFeaturesTrialsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/features/usage-billing': {
      id: '/_landing/features/usage-billing'
      path: '/features/usage-billing'
      fullPath: '/features/usage-billing'
      preLoaderRoute: typeof LandingFeaturesUsageBillingRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/legal/': {
      id: '/_landing/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LandingLegalIndexRouteImport
      parentRoute: typeof LandingLegalRoute
    }
    '/_landing/legal/acceptable-use-policy': {
      id: '/_landing/legal/acceptable-use-policy'
      path: '/acceptable-use-policy'
      fullPath: '/legal/acceptable-use-policy'
      preLoaderRoute: typeof LandingLegalAcceptableUsePolicyRouteImport
      parentRoute: typeof LandingLegalRoute
    }
    '/_landing/legal/checkout-buyer-terms': {
      id: '/_landing/legal/checkout-buyer-terms'
      path: '/checkout-buyer-terms'
      fullPath: '/legal/checkout-buyer-terms'
      preLoaderRoute: typeof LandingLegalCheckoutBuyerTermsRouteImport
      parentRoute: typeof LandingLegalRoute
    }
    '/_landing/legal/data-processing-addendum': {
      id: '/_landing/legal/data-processing-addendum'
      path: '/data-processing-addendum'
      fullPath: '/legal/data-processing-addendum'
      preLoaderRoute: typeof LandingLegalDataProcessingAddendumRouteImport
      parentRoute: typeof LandingLegalRoute
    }
    '/_landing/legal/master-services-terms': {
      id: '/_landing/legal/master-services-terms'
      path: '/master-services-terms'
      fullPath: '/legal/master-services-terms'
      preLoaderRoute: typeof LandingLegalMasterServicesTermsRouteImport
      parentRoute: typeof LandingLegalRoute
    }
    '/_landing/legal/payment-processor-partners': {
      id: '/_landing/legal/payment-processor-partners'
      path: '/payment-processor-partners'
      fullPath: '/legal/payment-processor-partners'
      preLoaderRoute: typeof LandingLegalPaymentProcessorPartnersRouteImport
      parentRoute: typeof LandingLegalRoute
    }
    '/_landing/legal/privacy-policy': {
      id: '/_landing/legal/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LandingLegalPrivacyPolicyRouteImport
      parentRoute: typeof LandingLegalRoute
    }
    '/_landing/legal/sub-processors': {
      id: '/_landing/legal/sub-processors'
      path: '/sub-processors'
      fullPath: '/legal/sub-processors'
      preLoaderRoute: typeof LandingLegalSubProcessorsRouteImport
      parentRoute: typeof LandingLegalRoute
    }
    '/_landing/resources/': {
      id: '/_landing/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof LandingResourcesIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/resources/merchant-of-record': {
      id: '/_landing/resources/merchant-of-record'
      path: '/resources/merchant-of-record'
      fullPath: '/resources/merchant-of-record'
      preLoaderRoute: typeof LandingResourcesMerchantOfRecordRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/resources/pricing': {
      id: '/_landing/resources/pricing'
      path: '/resources/pricing'
      fullPath: '/resources/pricing'
      preLoaderRoute: typeof LandingResourcesPricingRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/resources/why': {
      id: '/_landing/resources/why'
      path: '/resources/why'
      fullPath: '/resources/why'
      preLoaderRoute: typeof LandingResourcesWhyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/auth/sso/$slug': {
      id: '/auth/sso/$slug'
      path: '/sso/$slug'
      fullPath: '/auth/sso/$slug'
      preLoaderRoute: typeof AuthSsoSlugRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard/$organization/': {
      id: '/_authenticated/dashboard/$organization/'
      path: '/'
      fullPath: '/dashboard/$organization/'
      preLoaderRoute: typeof AuthenticatedDashboardOrganizationIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardOrganizationRoute
    }
    '/_landing/resources/comparison/lemon-squeezy': {
      id: '/_landing/resources/comparison/lemon-squeezy'
      path: '/resources/comparison/lemon-squeezy'
      fullPath: '/resources/comparison/lemon-squeezy'
      preLoaderRoute: typeof LandingResourcesComparisonLemonSqueezyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/resources/comparison/paddle': {
      id: '/_landing/resources/comparison/paddle'
      path: '/resources/comparison/paddle'
      fullPath: '/resources/comparison/paddle'
      preLoaderRoute: typeof LandingResourcesComparisonPaddleRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/resources/comparison/stripe': {
      id: '/_landing/resources/comparison/stripe'
      path: '/resources/comparison/stripe'
      fullPath: '/resources/comparison/stripe'
      preLoaderRoute: typeof LandingResourcesComparisonStripeRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_authenticated/dashboard/$organization/products/': {
      id: '/_authenticated/dashboard/$organization/products/'
      path: '/products'
      fullPath: '/dashboard/$organization/products/'
      preLoaderRoute: typeof AuthenticatedDashboardOrganizationProductsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardOrganizationRoute
    }
  }
}

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingProductRoute: typeof AuthenticatedOnboardingProductRoute
  AuthenticatedOnboardingValidateDescriptionRoute: typeof AuthenticatedOnboardingValidateDescriptionRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingProductRoute: AuthenticatedOnboardingProductRoute,
    AuthenticatedOnboardingValidateDescriptionRoute:
      AuthenticatedOnboardingValidateDescriptionRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedDashboardOrganizationRouteChildren {
  AuthenticatedDashboardOrganizationIndexRoute: typeof AuthenticatedDashboardOrganizationIndexRoute
  AuthenticatedDashboardOrganizationProductsIndexRoute: typeof AuthenticatedDashboardOrganizationProductsIndexRoute
}

const AuthenticatedDashboardOrganizationRouteChildren: AuthenticatedDashboardOrganizationRouteChildren =
  {
    AuthenticatedDashboardOrganizationIndexRoute:
      AuthenticatedDashboardOrganizationIndexRoute,
    AuthenticatedDashboardOrganizationProductsIndexRoute:
      AuthenticatedDashboardOrganizationProductsIndexRoute,
  }

const AuthenticatedDashboardOrganizationRouteWithChildren =
  AuthenticatedDashboardOrganizationRoute._addFileChildren(
    AuthenticatedDashboardOrganizationRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
  AuthenticatedDashboardOrganizationRoute: typeof AuthenticatedDashboardOrganizationRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
  AuthenticatedDashboardOrganizationRoute:
    AuthenticatedDashboardOrganizationRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LandingBlogRouteChildren {
  LandingBlogIntroducingPolarPlansRoute: typeof LandingBlogIntroducingPolarPlansRoute
  LandingBlogMitchellHashimotoJoinsPolarAsAnAdvisorRoute: typeof LandingBlogMitchellHashimotoJoinsPolarAsAnAdvisorRoute
  LandingBlogOrbitLlmSafeDesignSystemRoute: typeof LandingBlogOrbitLlmSafeDesignSystemRoute
  LandingBlogPolarSeedAnnouncementRoute: typeof LandingBlogPolarSeedAnnouncementRoute
  LandingBlogPromptAStartup2026Route: typeof LandingBlogPromptAStartup2026Route
  LandingBlogIndexRoute: typeof LandingBlogIndexRoute
}

const LandingBlogRouteChildren: LandingBlogRouteChildren = {
  LandingBlogIntroducingPolarPlansRoute: LandingBlogIntroducingPolarPlansRoute,
  LandingBlogMitchellHashimotoJoinsPolarAsAnAdvisorRoute:
    LandingBlogMitchellHashimotoJoinsPolarAsAnAdvisorRoute,
  LandingBlogOrbitLlmSafeDesignSystemRoute:
    LandingBlogOrbitLlmSafeDesignSystemRoute,
  LandingBlogPolarSeedAnnouncementRoute: LandingBlogPolarSeedAnnouncementRoute,
  LandingBlogPromptAStartup2026Route: LandingBlogPromptAStartup2026Route,
  LandingBlogIndexRoute: LandingBlogIndexRoute,
}

const LandingBlogRouteWithChildren = LandingBlogRoute._addFileChildren(
  LandingBlogRouteChildren,
)

interface LandingLegalRouteChildren {
  LandingLegalAcceptableUsePolicyRoute: typeof LandingLegalAcceptableUsePolicyRoute
  LandingLegalCheckoutBuyerTermsRoute: typeof LandingLegalCheckoutBuyerTermsRoute
  LandingLegalDataProcessingAddendumRoute: typeof LandingLegalDataProcessingAddendumRoute
  LandingLegalMasterServicesTermsRoute: typeof LandingLegalMasterServicesTermsRoute
  LandingLegalPaymentProcessorPartnersRoute: typeof LandingLegalPaymentProcessorPartnersRoute
  LandingLegalPrivacyPolicyRoute: typeof LandingLegalPrivacyPolicyRoute
  LandingLegalSubProcessorsRoute: typeof LandingLegalSubProcessorsRoute
  LandingLegalIndexRoute: typeof LandingLegalIndexRoute
}

const LandingLegalRouteChildren: LandingLegalRouteChildren = {
  LandingLegalAcceptableUsePolicyRoute: LandingLegalAcceptableUsePolicyRoute,
  LandingLegalCheckoutBuyerTermsRoute: LandingLegalCheckoutBuyerTermsRoute,
  LandingLegalDataProcessingAddendumRoute:
    LandingLegalDataProcessingAddendumRoute,
  LandingLegalMasterServicesTermsRoute: LandingLegalMasterServicesTermsRoute,
  LandingLegalPaymentProcessorPartnersRoute:
    LandingLegalPaymentProcessorPartnersRoute,
  LandingLegalPrivacyPolicyRoute: LandingLegalPrivacyPolicyRoute,
  LandingLegalSubProcessorsRoute: LandingLegalSubProcessorsRoute,
  LandingLegalIndexRoute: LandingLegalIndexRoute,
}

const LandingLegalRouteWithChildren = LandingLegalRoute._addFileChildren(
  LandingLegalRouteChildren,
)

interface LandingRouteChildren {
  LandingBlogRoute: typeof LandingBlogRouteWithChildren
  LandingCompanyRoute: typeof LandingCompanyRoute
  LandingDownloadsRoute: typeof LandingDownloadsRoute
  LandingLegalRoute: typeof LandingLegalRouteWithChildren
  LandingStartupProgramRoute: typeof LandingStartupProgramRoute
  LandingIndexRoute: typeof LandingIndexRoute
  LandingCustomersStillaAiRoute: typeof LandingCustomersStillaAiRoute
  LandingFeaturesCostInsightsRoute: typeof LandingFeaturesCostInsightsRoute
  LandingFeaturesCreditsRoute: typeof LandingFeaturesCreditsRoute
  LandingFeaturesDiscountsRoute: typeof LandingFeaturesDiscountsRoute
  LandingFeaturesFinanceRoute: typeof LandingFeaturesFinanceRoute
  LandingFeaturesMerchantOfRecordRoute: typeof LandingFeaturesMerchantOfRecordRoute
  LandingFeaturesSeatsRoute: typeof LandingFeaturesSeatsRoute
  LandingFeaturesSubscriptionsRoute: typeof LandingFeaturesSubscriptionsRoute
  LandingFeaturesTrialsRoute: typeof LandingFeaturesTrialsRoute
  LandingFeaturesUsageBillingRoute: typeof LandingFeaturesUsageBillingRoute
  LandingResourcesMerchantOfRecordRoute: typeof LandingResourcesMerchantOfRecordRoute
  LandingResourcesPricingRoute: typeof LandingResourcesPricingRoute
  LandingResourcesWhyRoute: typeof LandingResourcesWhyRoute
  LandingResourcesIndexRoute: typeof LandingResourcesIndexRoute
  LandingResourcesComparisonLemonSqueezyRoute: typeof LandingResourcesComparisonLemonSqueezyRoute
  LandingResourcesComparisonPaddleRoute: typeof LandingResourcesComparisonPaddleRoute
  LandingResourcesComparisonStripeRoute: typeof LandingResourcesComparisonStripeRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingBlogRoute: LandingBlogRouteWithChildren,
  LandingCompanyRoute: LandingCompanyRoute,
  LandingDownloadsRoute: LandingDownloadsRoute,
  LandingLegalRoute: LandingLegalRouteWithChildren,
  LandingStartupProgramRoute: LandingStartupProgramRoute,
  LandingIndexRoute: LandingIndexRoute,
  LandingCustomersStillaAiRoute: LandingCustomersStillaAiRoute,
  LandingFeaturesCostInsightsRoute: LandingFeaturesCostInsightsRoute,
  LandingFeaturesCreditsRoute: LandingFeaturesCreditsRoute,
  LandingFeaturesDiscountsRoute: LandingFeaturesDiscountsRoute,
  LandingFeaturesFinanceRoute: LandingFeaturesFinanceRoute,
  LandingFeaturesMerchantOfRecordRoute: LandingFeaturesMerchantOfRecordRoute,
  LandingFeaturesSeatsRoute: LandingFeaturesSeatsRoute,
  LandingFeaturesSubscriptionsRoute: LandingFeaturesSubscriptionsRoute,
  LandingFeaturesTrialsRoute: LandingFeaturesTrialsRoute,
  LandingFeaturesUsageBillingRoute: LandingFeaturesUsageBillingRoute,
  LandingResourcesMerchantOfRecordRoute: LandingResourcesMerchantOfRecordRoute,
  LandingResourcesPricingRoute: LandingResourcesPricingRoute,
  LandingResourcesWhyRoute: LandingResourcesWhyRoute,
  LandingResourcesIndexRoute: LandingResourcesIndexRoute,
  LandingResourcesComparisonLemonSqueezyRoute:
    LandingResourcesComparisonLemonSqueezyRoute,
  LandingResourcesComparisonPaddleRoute: LandingResourcesComparisonPaddleRoute,
  LandingResourcesComparisonStripeRoute: LandingResourcesComparisonStripeRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

interface AuthRouteChildren {
  AuthBackupCodesRoute: typeof AuthBackupCodesRoute
  AuthEmailOtpRoute: typeof AuthEmailOtpRoute
  AuthTotpRoute: typeof AuthTotpRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthSsoSlugRoute: typeof AuthSsoSlugRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBackupCodesRoute: AuthBackupCodesRoute,
  AuthEmailOtpRoute: AuthEmailOtpRoute,
  AuthTotpRoute: AuthTotpRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthSsoSlugRoute: AuthSsoSlugRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LandingRoute: LandingRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiStartupProgramRoute: ApiStartupProgramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
